import os
import shutil
import glob

def clean_artifacts():
    """
    Removes files and directories generated by PyInstaller and the Graber script.
    This includes 'dist/', 'build/', '.spec' files, and Graber output.
    """
    print("Starting cleanup...")

    # --- PyInstaller Artifacts ---
    print("Cleaning PyInstaller artifacts...")
    pyinstaller_dirs = ['dist', 'build']
    for dir_name in pyinstaller_dirs:
        if os.path.exists(dir_name) and os.path.isdir(dir_name):
            print(f"Removing directory: {dir_name}/")
            shutil.rmtree(dir_name)
        else:
            print(f"Directory not found (skipping): {dir_name}/")

    pyinstaller_files = glob.glob('*.spec')
    for file_path in pyinstaller_files:
        if os.path.exists(file_path) and os.path.isfile(file_path):
            print(f"Removing file: {file_path}")
            os.remove(file_path)
        else:
            print(f"File not found (skipping): {file_path}")

    # --- Graber Script Artifacts ---
    print("\nCleaning Graber script artifacts...")
    home_dir = os.path.expanduser('~')
    graber_dir = os.path.join(home_dir, 'G_LoggerExport')
    graber_zip = os.path.join(home_dir, 'G_LoggerExport.zip')

    # Remove Graber directory
    if os.path.exists(graber_dir) and os.path.isdir(graber_dir):
        print(f"Removing directory: {graber_dir}")
        shutil.rmtree(graber_dir)
    else:
        print(f"Directory not found (skipping): {graber_dir}")

    # Remove Graber zip file
    if os.path.exists(graber_zip) and os.path.isfile(graber_zip):
        print(f"Removing file: {graber_zip}")
        os.remove(graber_zip)
    else:
        print(f"File not found (skipping): {graber_zip}")
    
    # --- Specific file cleanup ---
    print("\nCleaning specific files...")
    graber_py_file = "Graber.py"
    if os.path.exists(graber_py_file) and os.path.isfile(graber_py_file):
        print(f"Removing file: {graber_py_file}")
        os.remove(graber_py_file)
    else:
        print(f"File not found (skipping): {graber_py_file}")

    print("\nCleanup complete.")

if __name__ == "__main__":
    clean_artifacts()
